title: Marc Aube
description: Software craftsmanship, rants and randomness

exclude: [README.md]

url: http://marcaube.ca
baseurl: ""
paginate_path: "/page/page:num/"
permalink: /:categories/:year/:month/:title

plugins: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
paginate: 5

navigation:
    - title: Home
      url: /
    - title: Articles
      url: /articles
    - title: Talks
      url: /talks
    - title: My bookshelf
      url: /books
# - title: About
#   url: /about
# - title: Contact
#   url: /contact

social:
   github: marcaube
   twitter: maaube
   disqus: marcaube

github:
    repository_url: https://github.com/marcaube/marcaube.github.io
